
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastrosService", targetNamespace = "http://server/", wsdlLocation = "http://EREBUS:8080/trabalho6/CadastrosService?wsdl")
public class CadastrosService
    extends Service
{

    private final static URL CADASTROSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CADASTROSSERVICE_EXCEPTION;
    private final static QName CADASTROSSERVICE_QNAME = new QName("http://server/", "CadastrosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://EREBUS:8080/trabalho6/CadastrosService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTROSSERVICE_WSDL_LOCATION = url;
        CADASTROSSERVICE_EXCEPTION = e;
    }

    public CadastrosService() {
        super(__getWsdlLocation(), CADASTROSSERVICE_QNAME);
    }

    public CadastrosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTROSSERVICE_QNAME, features);
    }

    public CadastrosService(URL wsdlLocation) {
        super(wsdlLocation, CADASTROSSERVICE_QNAME);
    }

    public CadastrosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTROSSERVICE_QNAME, features);
    }

    public CadastrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastrosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cadastros
     */
    @WebEndpoint(name = "CadastrosPort")
    public Cadastros getCadastrosPort() {
        return super.getPort(new QName("http://server/", "CadastrosPort"), Cadastros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cadastros
     */
    @WebEndpoint(name = "CadastrosPort")
    public Cadastros getCadastrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "CadastrosPort"), Cadastros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTROSSERVICE_EXCEPTION!= null) {
            throw CADASTROSSERVICE_EXCEPTION;
        }
        return CADASTROSSERVICE_WSDL_LOCATION;
    }

}
