
package server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DatabaseErrorException", targetNamespace = "http://server/")
public class DatabaseErrorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatabaseErrorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatabaseErrorException_Exception(String message, DatabaseErrorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatabaseErrorException_Exception(String message, DatabaseErrorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.DatabaseErrorException
     */
    public DatabaseErrorException getFaultInfo() {
        return faultInfo;
    }

}
