
package server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EventNotFoundException", targetNamespace = "http://server/")
public class EventNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventNotFoundException_Exception(String message, EventNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EventNotFoundException_Exception(String message, EventNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.EventNotFoundException
     */
    public EventNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
