
package trab;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://trab/")
@XmlSeeAlso({ ObjectFactory.class })
public interface Server {

	/**
	 * 
	 * @param text
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(name = "UF", targetNamespace = "")
	@RequestWrapper(localName = "obtemUF", targetNamespace = "http://trab/", className = "trab.ObtemUF")
	@ResponseWrapper(localName = "obtemUFResponse", targetNamespace = "http://trab/", className = "trab.ObtemUFResponse")
	@Action(input = "http://trab/Server/obtemUFRequest", output = "http://trab/Server/obtemUFResponse")
	public List<String> obtemUF(@WebParam(name = "text", targetNamespace = "") String text);

	/**
	 * 
	 * @param text
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "regiao", targetNamespace = "")
	@RequestWrapper(localName = "obtemRegiao", targetNamespace = "http://trab/", className = "trab.ObtemRegiao")
	@ResponseWrapper(localName = "obtemRegiaoResponse", targetNamespace = "http://trab/", className = "trab.ObtemRegiaoResponse")
	@Action(input = "http://trab/Server/obtemRegiaoRequest", output = "http://trab/Server/obtemRegiaoResponse")
	public String obtemRegiao(@WebParam(name = "text", targetNamespace = "") String text);

}
