
package webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaIngressosWebService", targetNamespace = "http://WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaIngressosWebService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns webservices.Token
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pedidoCompraLugar", targetNamespace = "http://WebServices/", className = "webservices.PedidoCompraLugar")
    @ResponseWrapper(localName = "pedidoCompraLugarResponse", targetNamespace = "http://WebServices/", className = "webservices.PedidoCompraLugarResponse")
    @Action(input = "http://WebServices/VendaIngressosWebService/pedidoCompraLugarRequest", output = "http://WebServices/VendaIngressosWebService/pedidoCompraLugarResponse")
    public Token pedidoCompraLugar(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        CartaoCredito arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "incluiEvento", targetNamespace = "http://WebServices/", className = "webservices.IncluiEvento")
    @ResponseWrapper(localName = "incluiEventoResponse", targetNamespace = "http://WebServices/", className = "webservices.IncluiEventoResponse")
    @Action(input = "http://WebServices/VendaIngressosWebService/incluiEventoRequest", output = "http://WebServices/VendaIngressosWebService/incluiEventoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://WebServices/VendaIngressosWebService/incluiEvento/Fault/Exception")
    })
    public void incluiEvento(
        @WebParam(name = "arg0", targetNamespace = "")
        Evento arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        LocalDateTime arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        LocalDateTime arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.Lugar>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaLugares", targetNamespace = "http://WebServices/", className = "webservices.ListaLugares")
    @ResponseWrapper(localName = "listaLugaresResponse", targetNamespace = "http://WebServices/", className = "webservices.ListaLugaresResponse")
    @Action(input = "http://WebServices/VendaIngressosWebService/listaLugaresRequest", output = "http://WebServices/VendaIngressosWebService/listaLugaresResponse")
    public List<Lugar> listaLugares(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<webservices.Evento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaEventos", targetNamespace = "http://WebServices/", className = "webservices.ListaEventos")
    @ResponseWrapper(localName = "listaEventosResponse", targetNamespace = "http://WebServices/", className = "webservices.ListaEventosResponse")
    @Action(input = "http://WebServices/VendaIngressosWebService/listaEventosRequest", output = "http://WebServices/VendaIngressosWebService/listaEventosResponse")
    public List<Evento> listaEventos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        LocalDate arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
